[project]
name = "chronicle"
version = "0.1.0"
description = "Chronicle is a Web application + Command line interface tool used to track daily logs related to work and other stuff."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.135.2",
    "sqlalchemy>=2.0.48",
]
